apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "time-tracker.fullname" . }}
  labels:
    {{- include "time-tracker.labels" . | nindent 4 }}
spec:
  entryPoints:
    - {{ .Values.ingress.entryPoint }}
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ include "time-tracker.fullname" . }}
          port: {{ .Values.service.port }}
  tls: {}
